---
- name: install/start httpd
  hosts: webservers
  become: true
  tasks:
  - name: 
    package:
      name: "{{ apache_package }}"
      state: absent 

#  - name: start/enable
#    service:
#      name: "{{ apache_service }}"
#      state: started
#      enabled: true